name: 自动同步上游仓库

on:
  # 手动触发
  workflow_dispatch:
  # 定时自动同步（每天 UTC 0点，即北京时间 8点）
  schedule:
    - cron: '0 0 1 * *' # 每月执行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史

      - name: 同步上游主分支
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          # ======================
          # 【这里必须改成原作者的仓库地址】
          upstream_repository: MarSeventh/CloudFlare-ImgBed
          # ======================
          upstream_branch: main  # 上游默认分支（一般是 main / master）
          target_branch: main    # 你的分支（和上游保持一致）
          git_pull_args: --allow-unrelated-histories
